package org.tinystruct.data.tools;

import org.junit.jupiter.api.Test;
import org.tinystruct.ApplicationRuntimeException;
import org.tinystruct.data.component.FieldInfo;
import org.tinystruct.data.repository.Type;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

public class TableCreatorTest {

    private static FieldInfo column(String column, String type, int length) {
        FieldInfo info = new FieldInfo();
        info.append("name", column);
        info.append("column", column);
        info.append("type", type);
        info.append("length", length);
        return info;
    }

    private static FieldInfo id(String type, boolean increment) {
        FieldInfo info = column("id", type, 0);
        info.append("increment", increment);
        return info;
    }

    private static List<FieldInfo> widgetColumns() {
        return Arrays.asList(
                column("name", "VARCHAR", 64),
                column("bio", "TEXT", 0),
                column("born", "DATE", 0),
                column("updated", "TIMESTAMP", 0),
                column("active", "BIT", 1));
    }

    @Test
    public void testMySQL() {
        assertEquals("CREATE TABLE IF NOT EXISTS `widgets` (`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, "
                        + "`name` VARCHAR(64), `bio` TEXT, `born` DATE, `updated` DATETIME, `active` BOOLEAN)",
                TableCreator.createStatement(Type.MySQL, "`widgets`", id("INTEGER", true), widgetColumns()));
    }

    @Test
    public void testPostgreSQL() {
        assertEquals("CREATE TABLE IF NOT EXISTS widgets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "name VARCHAR(64), bio TEXT, born DATE, updated TIMESTAMP, active BOOLEAN)",
                TableCreator.createStatement(Type.PostgreSQL, "widgets", id("INTEGER", true), widgetColumns()));
    }

    @Test
    public void testH2() {
        assertEquals("CREATE TABLE IF NOT EXISTS widgets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "name VARCHAR(64), bio TEXT, born DATE, updated TIMESTAMP, active BOOLEAN)",
                TableCreator.createStatement(Type.H2, "widgets", id("INTEGER", true), widgetColumns()));
    }

    @Test
    public void testSQLite() {
        assertEquals("CREATE TABLE IF NOT EXISTS widgets (id INTEGER PRIMARY KEY AUTOINCREMENT, "
                        + "name VARCHAR(64), bio TEXT, born DATE, updated TIMESTAMP, active BOOLEAN)",
                TableCreator.createStatement(Type.SQLite, "widgets", id("INTEGER", true), widgetColumns()));
    }

    @Test
    public void testSQLServerGuardsWithObjectId() {
        assertEquals("IF OBJECT_ID(N'[widgets]', N'U') IS NULL CREATE TABLE [widgets] ("
                        + "[id] INTEGER IDENTITY(1,1) PRIMARY KEY, [name] VARCHAR(64), [bio] VARCHAR(MAX), "
                        + "[born] DATE, [updated] DATETIME2, [active] BIT)",
                TableCreator.createStatement(Type.SQLServer, "[widgets]", id("INTEGER", true), widgetColumns()));
    }

    @Test
    public void testSchemaQualifiedTableIsUsedAsGiven() {
        assertEquals("CREATE TABLE IF NOT EXISTS \"public\".\"profiles\" (id BIGINT NOT NULL PRIMARY KEY)",
                TableCreator.createStatement(Type.PostgreSQL, "\"public\".\"profiles\"", id("BIGINT", false),
                        Collections.emptyList()));
    }

    @Test
    public void testNonIncrementIdIsAPlainPrimaryKey() {
        FieldInfo uuid = column("id", "VARCHAR", 36);

        assertEquals("CREATE TABLE IF NOT EXISTS sessions (id VARCHAR(36) NOT NULL PRIMARY KEY)",
                TableCreator.createStatement(Type.H2, "sessions", uuid, Collections.emptyList()));
    }

    @Test
    public void testTableWithoutIdentifier() {
        assertEquals("CREATE TABLE IF NOT EXISTS logs (message TEXT)",
                TableCreator.createStatement(Type.H2, "logs", null, Collections.singletonList(column("message", "TEXT", 0))));
    }

    @Test
    public void testVarcharWithoutLengthGetsADefault() {
        assertEquals("CREATE TABLE IF NOT EXISTS t (a VARCHAR(255), b CHAR(1))",
                TableCreator.createStatement(Type.H2, "t", null,
                        Arrays.asList(column("a", "VARCHAR", 0), column("b", "CHAR", 0))));
    }

    @Test
    public void testTypesAreRenderedPerDialect() {
        List<FieldInfo> columns = Arrays.asList(
                column("d", "DOUBLE", 0), column("j", "JSON", 0), column("u", "UUID", 0),
                column("b", "BLOB", 0), column("t", "LONGTEXT", 0), column("y", "TINYINT", 0));

        assertEquals("CREATE TABLE IF NOT EXISTS t (`d` DOUBLE, `j` JSON, `u` CHAR(36), `b` BLOB, `t` LONGTEXT, `y` TINYINT)",
                TableCreator.createStatement(Type.MySQL, "t", null, columns));
        assertEquals("CREATE TABLE IF NOT EXISTS t (d DOUBLE PRECISION, j JSON, u UUID, b BYTEA, t TEXT, y SMALLINT)",
                TableCreator.createStatement(Type.PostgreSQL, "t", null, columns));
        assertEquals("IF OBJECT_ID(N't', N'U') IS NULL CREATE TABLE t ([d] FLOAT, [j] VARCHAR(MAX), [u] CHAR(36), "
                        + "[b] VARBINARY(MAX), [t] VARCHAR(MAX), [y] TINYINT)",
                TableCreator.createStatement(Type.SQLServer, "t", null, columns));
    }

    @Test
    public void testInvalidInputIsRejected() {
        List<FieldInfo> none = Collections.emptyList();

        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.Redis, "t", id("INTEGER", true), none));
        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.H2, "t; DROP TABLE users", id("INTEGER", true), none));
        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.H2, "t", null, Collections.singletonList(column("a b", "TEXT", 0))));
        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.H2, "t", null, Collections.singletonList(column("a", "OTHER", 0))));
        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.H2, "t", null, Collections.singletonList(new FieldInfo("a"))));
        assertThrows(ApplicationRuntimeException.class,
                () -> TableCreator.createStatement(Type.H2, "t", null, none), "a table needs at least one column");
    }

    private static List<FieldInfo> everyPortableType() {
        List<FieldInfo> columns = new ArrayList<>();
        int n = 0;
        for (String type : new String[]{"INT", "BIGINT", "SMALLINT", "TINYINT", "BIT", "FLOAT", "REAL", "DOUBLE",
                "DECIMAL", "VARCHAR", "CHAR", "TEXT", "LONGTEXT", "UUID", "JSON", "DATE", "TIME", "TIMESTAMP", "BLOB"}) {
            columns.add(column("c" + n++, type, 10));
        }
        return columns;
    }

    private static List<String> columnNames(Connection connection, String table) throws SQLException {
        List<String> names = new ArrayList<>();
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, table, null)) {
            while (columns.next()) {
                names.add(columns.getString("COLUMN_NAME").toLowerCase());
            }
        }
        return names;
    }

    @Test
    public void testStatementRunsOnH2AndIsIdempotent() throws SQLException {
        String sql = TableCreator.createStatement(Type.H2, "TABLE_CREATOR_H2", id("INTEGER", true), everyPortableType());

        try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:tablecreator;DB_CLOSE_DELAY=-1");
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
            statement.execute(sql); // a second start-up must be harmless

            List<String> names = columnNames(connection, "TABLE_CREATOR_H2");
            assertEquals(1 + everyPortableType().size(), names.size());
            assertTrue(names.contains("id") && names.contains("c0") && names.contains("c18"), names.toString());

            // The identity column generates its own values.
            statement.execute("INSERT INTO TABLE_CREATOR_H2 (c9) VALUES ('a')");
            statement.execute("INSERT INTO TABLE_CREATOR_H2 (c9) VALUES ('b')");
            try (ResultSet rows = statement.executeQuery("SELECT MAX(id) FROM TABLE_CREATOR_H2")) {
                rows.next();
                assertEquals(2, rows.getInt(1));
            }
        }
    }

    @Test
    public void testStatementRunsOnSQLiteAndIsIdempotent() throws SQLException {
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException e) {
            assumeTrue(false, "SQLite driver is not on the classpath");
        }

        String sql = TableCreator.createStatement(Type.SQLite, "table_creator_sqlite", id("INTEGER", true), everyPortableType());

        try (Connection connection = DriverManager.getConnection("jdbc:sqlite::memory:");
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
            statement.execute(sql);

            assertEquals(1 + everyPortableType().size(), columnNames(connection, "table_creator_sqlite").size());

            statement.execute("INSERT INTO table_creator_sqlite (c9) VALUES ('a')");
            statement.execute("INSERT INTO table_creator_sqlite (c9) VALUES ('b')");
            try (ResultSet rows = statement.executeQuery("SELECT MAX(id) FROM table_creator_sqlite")) {
                rows.next();
                assertEquals(2, rows.getInt(1));
            }
        }
    }
}
