package org.tinystruct.data.component;

import org.junit.jupiter.api.Test;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.*;

public class FieldInfoTest {

    @Test
    void defaultConstructorHasSaneDefaults() {
        FieldInfo field = new FieldInfo();
        assertNull(field.getName());
        assertNull(field.getColumnName());
        assertEquals(0, field.getLength());
        assertFalse(field.autoIncrement());
        assertFalse(field.isAutoIncrement());
        assertFalse(field.isGenerate());
        assertFalse(field.isAutoGenerated());
        assertNull(field.getType());
        assertEquals("", field.getTypeName());
        assertNull(field.value());
    }

    @Test
    void nameConstructorSetsName() {
        FieldInfo field = new FieldInfo("email");
        assertEquals("email", field.getName());
    }

    @Test
    void settersAndGettersRoundTrip() {
        FieldInfo field = new FieldInfo();
        field.setName("name");
        field.setColumnName("user_name");
        field.setLength(255);
        field.setAutoIncrement(true);
        field.setAutoGenerated(true);
        field.setType(FieldType.VARCHAR);

        assertEquals("name", field.getName());
        assertEquals("user_name", field.getColumnName());
        assertEquals(255, field.getLength());
        assertTrue(field.autoIncrement());
        assertTrue(field.isAutoIncrement());
        assertTrue(field.isGenerate());
        assertTrue(field.isAutoGenerated());
        assertEquals(FieldType.VARCHAR, field.getType());
        assertEquals("VARCHAR", field.getTypeName());
    }

    @Test
    void appendDispatchesToTypedFields() {
        FieldInfo field = new FieldInfo();
        field.append("name", "id");
        field.append("column", "id");
        field.append("type", "int");
        field.append("length", "11");
        field.append("increment", "1");
        field.append("generate", "true");
        field.append("value", 42);

        assertEquals("id", field.getName());
        assertEquals("id", field.getColumnName());
        assertEquals(FieldType.INT, field.getType());
        assertEquals(11, field.getLength());
        assertTrue(field.autoIncrement());
        assertTrue(field.isGenerate());
        assertEquals(42, field.value());
    }

    @Test
    void setAcceptsFieldTypeInstanceDirectly() {
        FieldInfo field = new FieldInfo();
        field.set("type", FieldType.BIGINT);
        assertEquals(FieldType.BIGINT, field.getType());
    }

    @Test
    void idKeySetsNameForMappingXmlCompatibility() {
        FieldInfo field = new FieldInfo();
        field.append("id", "userId");
        assertEquals("userId", field.getName());
    }

    @Test
    void setIgnoresNullPropertyOrValue() {
        FieldInfo field = new FieldInfo();
        field.set("name", "keep-me");
        field.set(null, "ignored");
        field.set("name", null);
        assertEquals("keep-me", field.getName());
    }

    @Test
    void setIgnoresUnknownProperty() {
        FieldInfo field = new FieldInfo();
        assertDoesNotThrow(() -> field.set("unknown-key", "value"));
    }

    @Test
    void valueConversions() {
        FieldInfo field = new FieldInfo();
        field.set("value", "42.9");
        assertEquals("42.9", field.stringValue());
        assertEquals(42.9, field.doubleValue(), 0.0001);
        assertEquals(42, field.intValue());
        assertEquals(42L, field.longValue());
        assertEquals(42.9f, field.floatValue(), 0.0001f);
    }

    @Test
    void emptyValueConversionsReturnDefaults() {
        FieldInfo field = new FieldInfo();
        assertNull(field.stringValue());
        assertEquals(0, field.doubleValue());
        assertEquals(-1, field.intValue());
        assertEquals(-1L, field.longValue());
        assertEquals(0.0f, field.floatValue());
        assertFalse(field.booleanValue());
        assertNull(field.byteArrayValue());
    }

    @Test
    void booleanValueInterpretsOneAndZero() {
        FieldInfo field = new FieldInfo();
        field.set("value", "1");
        assertTrue(field.booleanValue());

        field.set("value", "0");
        assertFalse(field.booleanValue());

        field.set("value", "true");
        assertTrue(field.booleanValue());
    }

    @Test
    void byteArrayValueReturnsStoredBytes() {
        FieldInfo field = new FieldInfo();
        byte[] bytes = {1, 2, 3};
        field.set("value", bytes);
        assertArrayEquals(bytes, field.byteArrayValue());
    }

    @Test
    void timestampValueDefaultReturnsFallbackTimestamp() {
        FieldInfo field = new FieldInfo();
        assertEquals(Timestamp.valueOf("1982-03-20 00:00:00.0"), field.timestampValue());
    }

    @Test
    void timestampValueParsesStoredValue() {
        FieldInfo field = new FieldInfo();
        field.set("value", "2024-01-02 03:04:05.0");
        assertEquals(Timestamp.valueOf("2024-01-02 03:04:05.0"), field.timestampValue());

        field.set("value", "2024-01-02");
        assertEquals(Timestamp.valueOf("2024-01-02 00:00:00.0"), field.timestampValue());
    }

    @Test
    void convenienceConstructorsAndBeanProperties() {
        FieldInfo f1 = new FieldInfo("title", "Hello");
        assertEquals("title", f1.getName());
        assertEquals("Hello", f1.getValue());
        assertEquals("Hello", f1.value());

        FieldInfo f2 = new FieldInfo("count", 10, FieldType.INT);
        assertEquals("count", f2.getName());
        assertEquals(10, f2.getValue());
        assertEquals(FieldType.INT, f2.getType());

        f2.setAutoIncrement(true);
        assertTrue(f2.isAutoIncrement());

        f2.setValue(20);
        assertEquals(20, f2.getValue());
    }

    @Test
    void getFacadeDispatchesCorrectly() {
        FieldInfo field = new FieldInfo();
        field.setName("id");
        field.setColumnName("col_id");
        field.setValue(100);
        field.setType(FieldType.BIGINT);
        field.setLength(20);
        field.setAutoIncrement(true);
        field.setGenerate(true);

        assertEquals("id", field.get("name"));
        assertEquals("id", field.get("id"));
        assertEquals("col_id", field.get("column"));
        assertEquals(100, field.get("value"));
        assertEquals(FieldType.BIGINT, field.get("type"));
        assertEquals(20, field.get("length"));
        assertEquals(true, field.get("increment"));
        assertEquals(true, field.get("auto_increment"));
        assertEquals(true, field.get("generate"));
        assertNull(field.get("unknown_key"));
        assertNull(field.get(null));
    }

    @Test
    void dateValueReturnsStoredDateOrNewInstance() {
        FieldInfo field = new FieldInfo();
        Date now = new Date();
        field.set("value", now);
        assertEquals(now, field.dateValue());

        FieldInfo empty = new FieldInfo();
        assertNotNull(empty.dateValue());
    }

    @Test
    void localDateTimeValueSupportsMultipleSourceTypes() {
        LocalDateTime ldt = LocalDateTime.of(2024, 1, 2, 3, 4, 5);

        FieldInfo fromLdt = new FieldInfo();
        fromLdt.set("value", ldt);
        assertEquals(ldt, fromLdt.localDateTimeValue());

        FieldInfo fromTimestamp = new FieldInfo();
        fromTimestamp.set("value", Timestamp.valueOf(ldt));
        assertEquals(ldt, fromTimestamp.localDateTimeValue());

        FieldInfo fromString = new FieldInfo();
        fromString.set("value", "2024-01-02 03:04:05");
        assertEquals(ldt, fromString.localDateTimeValue());

        FieldInfo empty = new FieldInfo();
        assertNotNull(empty.localDateTimeValue());
    }

    @Test
    void typeOfInfersFieldTypeFromRuntimeClass() {
        FieldInfo field = new FieldInfo();
        assertEquals(FieldType.INTEGER, field.typeOf(1));
        assertEquals(FieldType.STRING, field.typeOf("s"));
        assertEquals(FieldType.DOUBLE, field.typeOf(1.0d));
        assertEquals(FieldType.FLOAT, field.typeOf(1.0f));
        assertEquals(FieldType.LONG, field.typeOf(1L));
        assertEquals(FieldType.BOOLEAN, field.typeOf(true));
        assertEquals(FieldType.DATE, field.typeOf(new Date()));
        assertEquals(FieldType.DATETIME, field.typeOf(LocalDateTime.now()));
        assertEquals(FieldType.STRING, field.typeOf(new Object()));
    }

    @Test
    void toStringProducesEscapedJsonFragmentForNonNullAttributes() {
        FieldInfo field = new FieldInfo();
        field.setName("na\"me");
        field.setColumnName("col");
        field.setType(FieldType.VARCHAR);
        field.setLength(10);
        field.setAutoIncrement(true);
        field.setGenerate(true);
        field.set("value", "va[l]ue");

        String json = field.toString();
        assertTrue(json.contains("\"name\":\"na\\\"me\""));
        assertTrue(json.contains("\"column\":\"col\""));
        assertTrue(json.contains("\"type\":\"VARCHAR\""));
        assertTrue(json.contains("\"length\":\"10\""));
        assertTrue(json.contains("\"increment\":\"true\""));
        assertTrue(json.contains("\"generate\":\"true\""));
        assertTrue(json.contains("\"value\":\"va\\[l\\]ue\""));
    }

    @Test
    void toStringOmitsUnsetAttributes() {
        FieldInfo field = new FieldInfo();
        field.setName("onlyName");
        assertEquals(" \"name\":\"onlyName\"", field.toString());
    }

    @Test
    void equalsAndHashCodeConsiderAllFields() {
        FieldInfo a = new FieldInfo("name");
        a.setColumnName("col");
        a.setLength(5);
        a.setAutoIncrement(true);
        a.setGenerate(true);
        a.setType(FieldType.INT);
        a.set("value", "v");

        FieldInfo b = new FieldInfo("name");
        b.setColumnName("col");
        b.setLength(5);
        b.setAutoIncrement(true);
        b.setGenerate(true);
        b.setType(FieldType.INT);
        b.set("value", "v");

        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode());

        b.setLength(6);
        assertNotEquals(a, b);
    }

    @Test
    void equalsHandlesSelfNullAndDifferentType() {
        FieldInfo field = new FieldInfo("name");
        assertEquals(field, field);
        assertNotEquals(null, field);
        assertNotEquals("not-a-field-info", field);
    }

    @Test
    void isSerializable() {
        assertTrue(java.io.Serializable.class.isAssignableFrom(FieldInfo.class));
    }
}
