/*******************************************************************************
 * Copyright  (c) 2013, 2026 James M. ZHOU
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package org.tinystruct.data.component;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Objects;

/**
 * Encapsulates the metadata and value for a single database column or entity field.
 * <p>
 * This class is designed as a high-performance, strongly-typed POJO replacing legacy
 * {@code HashMap} inheritance. It represents all column attributes as explicit Java fields
 * while retaining string-key dispatching methods ({@link #append(String, Object)},
 * {@link #set(String, Object)}, {@link #get(String)}) as a seamless compatibility facade.
 * </p>
 * <p>
 * Instances are designed for per-row mapping lifecycles and are not thread-safe.
 * </p>
 *
 * @author James Zhou
 */
public class FieldInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Default timestamp fallback (1982-03-20 00:00:00.0) used when value is empty or not set.
     */
    private static final Timestamp DEFAULT_TIMESTAMP = Timestamp.valueOf("1982-03-20 00:00:00.0");

    // -------------------------------------------------------------------------
    // Column descriptor fields
    // -------------------------------------------------------------------------

    /** The logical field / property name used in Java code. */
    private String name;

    /** The actual database column name. */
    private String column;

    /** The raw column value for this row. */
    private Object value;

    /** The resolved field type. */
    private FieldType type;

    /** Maximum column length or display size. */
    private int length;

    /** Whether this column is auto-incremented by the database. */
    private boolean autoIncrement;

    /**
     * Whether the ID for this field should be auto-generated (e.g. UUID strategy).
     * Corresponds to the XML mapping attribute {@code generate}.
     */
    private boolean autoGenerated;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Constructs an empty {@code FieldInfo} with default values.
     */
    public FieldInfo() {
        this.autoIncrement = false;
        this.autoGenerated = false;
        this.length = 0;
    }

    /**
     * Constructs a {@code FieldInfo} with the specified logical field name.
     *
     * @param name the field name
     */
    public FieldInfo(String name) {
        this();
        this.name = name;
    }

    /**
     * Constructs a {@code FieldInfo} with the specified field name and value.
     *
     * @param name  the field name
     * @param value the field value
     */
    public FieldInfo(String name, Object value) {
        this(name);
        this.value = value;
    }

    /**
     * Constructs a {@code FieldInfo} with the specified field name, value, and type.
     *
     * @param name  the field name
     * @param value the field value
     * @param type  the field type
     */
    public FieldInfo(String name, Object value, FieldType type) {
        this(name, value);
        this.type = type;
    }

    /**
     * Constructs a {@code FieldInfo} that copies the column descriptor (name, column,
     * type, length, increment and generate flags) of {@code prototype}. The value is
     * deliberately not copied, so each copy starts unset and is independent of the
     * prototype.
     *
     * @param prototype the descriptor to copy
     */
    public FieldInfo(FieldInfo prototype) {
        this.name = prototype.name;
        this.column = prototype.column;
        this.type = prototype.type;
        this.length = prototype.length;
        this.autoIncrement = prototype.autoIncrement;
        this.autoGenerated = prototype.autoGenerated;
    }

    // -------------------------------------------------------------------------
    // Compatibility facade — append / set / get dispatch
    // -------------------------------------------------------------------------

    /**
     * Compatibility facade: routes the given property key to the appropriate
     * typed setter. Equivalent to {@link #set(String, Object)}.
     *
     * @param property the property name (one of: name, column, value, type,
     *                 length, increment, generate, id)
     * @param val      the property value; ignored if {@code null}
     */
    public void append(String property, Object val) {
        set(property, val);
    }

    /**
     * Routes the given property key to the appropriate typed setter.
     * Case-insensitive for common property names. Unknown keys are silently ignored.
     *
     * @param property the property name
     * @param val      the property value; ignored if {@code null}
     */
    public void set(String property, Object val) {
        if (property == null || val == null) return;
        switch (property.toLowerCase()) {
            case "name":
            case "id":
                this.name = val.toString();
                break;
            case "column":
                this.column = val.toString();
                break;
            case "value":
                this.value = val;
                break;
            case "type":
                if (val instanceof FieldType) {
                    this.type = (FieldType) val;
                } else {
                    this.type = FieldType.valueOf(val.toString().trim());
                }
                break;
            case "length":
                if (val instanceof Number) {
                    this.length = ((Number) val).intValue();
                } else {
                    try {
                        this.length = Integer.parseInt(val.toString().trim());
                    } catch (NumberFormatException ignored) {
                        this.length = 0;
                    }
                }
                break;
            case "increment":
            case "auto_increment":
            case "autoincrement":
                if (val instanceof Boolean) {
                    this.autoIncrement = (Boolean) val;
                } else {
                    String inc = val.toString().trim();
                    this.autoIncrement = "1".equals(inc) || Boolean.parseBoolean(inc);
                }
                break;
            case "generate":
            case "autogenerated":
            case "auto_generated":
                if (val instanceof Boolean) {
                    this.autoGenerated = (Boolean) val;
                } else {
                    String gen = val.toString().trim();
                    this.autoGenerated = "1".equals(gen) || Boolean.parseBoolean(gen);
                }
                break;
            default:
                // Unknown property — silently ignore to allow forward compatibility.
                break;
        }
    }

    /**
     * Returns the property value for the given property name.
     * Provided as a string-key facade for backward compatibility.
     *
     * @param property the property name (case-insensitive)
     * @return the resolved property value, or {@code null} if unset or unknown
     */
    public Object get(String property) {
        if (property == null) return null;
        switch (property.toLowerCase()) {
            case "name":
            case "id":
                return this.name;
            case "column":
                return this.column;
            case "value":
                return this.value;
            case "type":
                return this.type;
            case "length":
                return this.length;
            case "increment":
            case "auto_increment":
            case "autoincrement":
                return this.autoIncrement;
            case "generate":
            case "autogenerated":
            case "auto_generated":
                return this.autoGenerated;
            default:
                return null;
        }
    }

    // -------------------------------------------------------------------------
    // Getters and setters
    // -------------------------------------------------------------------------

    /**
     * Returns the logical field / property name.
     *
     * @return the field name, or {@code null} if not set
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the logical field / property name.
     *
     * @param name the field name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the database column name.
     *
     * @return the column name, or {@code null} if not set
     */
    public String getColumnName() {
        return this.column;
    }

    /**
     * Sets the database column name.
     *
     * @param column the column name
     */
    public void setColumnName(String column) {
        this.column = column;
    }

    /**
     * Returns the column length or display size.
     *
     * @return the length, or {@code 0} if not set
     */
    public int getLength() {
        return this.length;
    }

    /**
     * Sets the column length or display size.
     *
     * @param length the column length
     */
    public void setLength(int length) {
        this.length = length;
    }

    /**
     * Returns whether this column uses database auto-increment.
     *
     * @return {@code true} if the column is auto-incremented
     */
    public boolean autoIncrement() {
        return this.autoIncrement;
    }

    /**
     * Returns whether this column uses database auto-increment.
     * Standard JavaBeans alias for {@link #autoIncrement()}.
     *
     * @return {@code true} if the column is auto-incremented
     */
    public boolean isAutoIncrement() {
        return this.autoIncrement;
    }

    /**
     * Sets whether this column uses database auto-increment.
     *
     * @param autoIncrement {@code true} to mark the column as auto-incremented
     */
    public void setAutoIncrement(boolean autoIncrement) {
        this.autoIncrement = autoIncrement;
    }

    /**
     * Returns whether an application-level ID (e.g. UUID) should be auto-generated
     * for this field before insertion.
     *
     * @return {@code true} if an ID should be auto-generated
     */
    public boolean isAutoGenerated() {
        return this.autoGenerated;
    }

    /**
     * Sets whether an application-level ID should be auto-generated for this field.
     *
     * @param autoGenerated {@code true} to enable ID auto-generation
     */
    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    /**
     * Returns whether an application-level ID should be generated for this field.
     * Compatibility alias for {@link #isAutoGenerated()}.
     *
     * @return {@code true} if an ID should be auto-generated
     */
    public boolean isGenerate() {
        return this.autoGenerated;
    }

    /**
     * Sets whether an application-level ID should be generated for this field.
     * Compatibility alias for {@link #setAutoGenerated(boolean)}.
     *
     * @param generate {@code true} to enable ID auto-generation
     */
    public void setGenerate(boolean generate) {
        this.autoGenerated = generate;
    }

    /**
     * Returns the resolved {@link FieldType}.
     *
     * @return the field type, or {@code null} if not set
     */
    public FieldType getType() {
        return this.type;
    }

    /**
     * Returns the raw SQL type name string stored for this field, suitable for
     * embedding directly in SQL DDL / stored procedure parameter lists.
     * This is the string representation of the {@link FieldType} as it appears
     * in the mapping XML (e.g. {@code "int"}, {@code "nvarchar"}).
     *
     * @return the type name, or an empty string if not set
     */
    public String getTypeName() {
        return this.type != null ? this.type.getTypeName() : "";
    }

    /**
     * Sets the field type.
     *
     * @param type the {@link FieldType}
     */
    public void setType(FieldType type) {
        this.type = type;
    }

    // -------------------------------------------------------------------------
    // Value accessors
    // -------------------------------------------------------------------------

    /**
     * Returns the raw value associated with this field.
     *
     * @return the column value, or {@code null} if not set
     */
    public Object value() {
        return this.value;
    }

    /**
     * Returns the raw value associated with this field.
     * Standard JavaBeans getter for {@code value}.
     *
     * @return the column value, or {@code null} if not set
     */
    public Object getValue() {
        return this.value;
    }

    /**
     * Sets the raw value associated with this field.
     * Standard JavaBeans setter for {@code value}.
     *
     * @param value the value to set
     */
    public void setValue(Object value) {
        this.value = value;
    }

    /**
     * Returns the column value as a {@link String}.
     *
     * @return the string value, or {@code null} if the value is {@code null}
     */
    public String stringValue() {
        return this.value == null ? null : this.value.toString();
    }

    /**
     * Returns the column value as a {@code double}.
     *
     * @return the double value, or {@code 0.0d} if the value is {@code null} or empty
     */
    public double doubleValue() {
        if (this.value == null) return 0.0d;
        if (this.value instanceof Number) return ((Number) this.value).doubleValue();
        String s = this.value.toString().trim();
        return s.isEmpty() ? 0.0d : Double.parseDouble(s);
    }

    /**
     * Returns the column value as an {@code int}.
     * Truncates any decimal portion present in the string representation.
     *
     * @return the integer value, or {@code -1} if the value is {@code null} or unparseable
     */
    public int intValue() {
        if (this.value == null) return -1;
        if (this.value instanceof Number) return ((Number) this.value).intValue();
        String s = this.value.toString().trim();
        if (s.isEmpty()) return -1;
        int dot = s.lastIndexOf('.');
        return Integer.parseInt(dot != -1 ? s.substring(0, dot) : s);
    }

    /**
     * Returns the column value as a {@code long}.
     * Truncates any decimal portion present in the string representation.
     *
     * @return the long value, or {@code -1} if the value is {@code null} or unparseable
     */
    public long longValue() {
        if (this.value == null) return -1;
        if (this.value instanceof Number) return ((Number) this.value).longValue();
        String s = this.value.toString().trim();
        if (s.isEmpty()) return -1;
        int dot = s.lastIndexOf('.');
        return Long.parseLong(dot != -1 ? s.substring(0, dot) : s);
    }

    /**
     * Returns the column value as a {@code float}.
     *
     * @return the float value, or {@code 0.0f} if the value is {@code null} or empty
     */
    public float floatValue() {
        if (this.value == null) return 0.0f;
        if (this.value instanceof Number) return ((Number) this.value).floatValue();
        String s = this.value.toString().trim();
        return s.isEmpty() ? 0.0f : Float.parseFloat(s);
    }

    /**
     * Returns the column value as a {@code boolean}.
     * Interprets {@code "1"} or {@code "true"} as {@code true},
     * {@code "0"} or {@code "false"} as {@code false};
     * non-zero numbers as {@code true}; otherwise delegates to {@link Boolean#parseBoolean(String)}.
     *
     * @return the boolean value, or {@code false} if the value is {@code null}
     */
    public boolean booleanValue() {
        if (this.value == null) return false;
        if (this.value instanceof Boolean) return (Boolean) this.value;
        if (this.value instanceof Number) return ((Number) this.value).intValue() != 0;
        String s = this.value.toString().trim();
        if ("1".equals(s) || "true".equalsIgnoreCase(s)) return true;
        if ("0".equals(s) || "false".equalsIgnoreCase(s)) return false;
        return Boolean.parseBoolean(s);
    }

    /**
     * Returns the column value cast to a {@code byte[]}.
     *
     * @return the byte array value, or {@code null} if the value is not a byte array
     */
    public byte[] byteArrayValue() {
        return (this.value instanceof byte[]) ? (byte[]) this.value : null;
    }

    /**
     * Returns the column value as a {@link Timestamp}.
     * Supports stored {@link Timestamp}, {@link Date}, {@link LocalDateTime},
     * epoch milliseconds ({@link Number}), or date-time strings.
     * Defaults to {@code Timestamp.valueOf("1982-03-20 00:00:00.0")} if the value is {@code null}.
     *
     * @return the {@link Timestamp} representation
     */
    public Timestamp timestampValue() {
        if (this.value == null) {
            return DEFAULT_TIMESTAMP;
        }
        if (this.value instanceof Timestamp) {
            return (Timestamp) this.value;
        }
        if (this.value instanceof Date) {
            return new Timestamp(((Date) this.value).getTime());
        }
        if (this.value instanceof LocalDateTime) {
            return Timestamp.valueOf((LocalDateTime) this.value);
        }
        if (this.value instanceof Number) {
            return new Timestamp(((Number) this.value).longValue());
        }

        String s = this.value.toString().trim();
        if (s.isEmpty()) {
            return DEFAULT_TIMESTAMP;
        }
        if (s.length() == 10) {
            s += " 00:00:00";
        } else if (s.indexOf('T') != -1) {
            s = s.replace('T', ' ');
        }
        return Timestamp.valueOf(s);
    }

    /**
     * Returns the column value as a {@link Date}.
     * Supports {@link Date}, {@link LocalDateTime}, or epoch milliseconds.
     * Returns a new {@link Date} instance if the stored value cannot be converted.
     *
     * @return the {@link Date} representation
     */
    public Date dateValue() {
        if (this.value instanceof Date) {
            return (Date) this.value;
        }
        if (this.value instanceof LocalDateTime) {
            return Timestamp.valueOf((LocalDateTime) this.value);
        }
        if (this.value instanceof Number) {
            return new Date(((Number) this.value).longValue());
        }
        return new Date();
    }

    /**
     * Returns the column value as a {@link LocalDateTime}.
     * Supports stored {@link LocalDateTime}, {@link java.sql.Timestamp}, {@link Date},
     * or ISO / space-delimited date-time strings. Falls back to
     * {@link LocalDateTime#now()} on parse failure or when the value is {@code null}.
     *
     * @return the {@link LocalDateTime} representation
     */
    public LocalDateTime localDateTimeValue() {
        if (this.value instanceof LocalDateTime) {
            return (LocalDateTime) this.value;
        }
        if (this.value instanceof java.sql.Timestamp) {
            return ((java.sql.Timestamp) this.value).toLocalDateTime();
        }
        if (this.value instanceof Date) {
            return new Timestamp(((Date) this.value).getTime()).toLocalDateTime();
        }
        if (this.value != null) {
            String s = this.value.toString().trim();
            if (!s.isEmpty()) {
                try {
                    return LocalDateTime.parse(s.replace(' ', 'T'));
                } catch (Exception ignored) {
                    // fall through to now()
                }
            }
        }
        return LocalDateTime.now();
    }

    // -------------------------------------------------------------------------
    // Type inference
    // -------------------------------------------------------------------------

    /**
     * Determines the {@link FieldType} that corresponds to the runtime type of
     * the given object.
     *
     * @param object the object to inspect
     * @return the resolved {@link FieldType}, defaulting to {@link FieldType#STRING}
     */
    public static FieldType typeOf(Object object) {
        if (object instanceof Integer)       return FieldType.INTEGER;
        if (object instanceof String)        return FieldType.STRING;
        if (object instanceof Double)        return FieldType.DOUBLE;
        if (object instanceof Float)         return FieldType.FLOAT;
        if (object instanceof Long)          return FieldType.LONG;
        if (object instanceof Boolean)       return FieldType.BOOLEAN;
        if (object instanceof Date)          return FieldType.DATE;
        if (object instanceof LocalDateTime) return FieldType.DATETIME;
        if (object instanceof Blob || object instanceof byte[]) return FieldType.BLOB;
        if (object instanceof BigDecimal)    return FieldType.DECIMAL;
        return FieldType.STRING;
    }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    /**
     * Returns a JSON-fragment string representation of this field info, with
     * special characters properly escaped.
     *
     * @return a JSON key-value fragment for all non-null attributes
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendJson(sb, "name",      this.name);
        appendJson(sb, "column",    this.column);
        appendJson(sb, "type",      this.type != null ? this.type.getTypeName() : null);
        appendJson(sb, "length",    this.length > 0 ? String.valueOf(this.length) : null);
        appendJson(sb, "increment", this.autoIncrement ? "true" : null);
        appendJson(sb, "generate",  this.autoGenerated ? "true" : null);
        appendJson(sb, "value",     this.value != null ? this.value.toString() : null);
        return sb.toString();
    }

    private static void appendJson(StringBuilder sb, String key, String raw) {
        if (raw == null) return;
        String escaped = raw
                .replace("\"", "\\\"")
                .replace("'",  "\\'")
                .replace("[",  "\\[")
                .replace("]",  "\\]")
                .replace("{",  "\\{")
                .replace("}",  "\\}");
        if (sb.length() > 0) {
            sb.append(", ");
        } else {
            sb.append(' ');
        }
        sb.append('"').append(key).append("\":\"").append(escaped).append('"');
    }

    @Override
    public int hashCode() {
        int result = Objects.hashCode(this.name);
        result = 31 * result + Objects.hashCode(this.column);
        result = 31 * result + Objects.hashCode(this.type);
        result = 31 * result + Objects.hashCode(this.value);
        result = 31 * result + Integer.hashCode(this.length);
        result = 31 * result + Boolean.hashCode(this.autoIncrement);
        result = 31 * result + Boolean.hashCode(this.autoGenerated);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof FieldInfo)) return false;
        FieldInfo other = (FieldInfo) obj;
        return this.length == other.length
                && this.autoIncrement == other.autoIncrement
                && this.autoGenerated == other.autoGenerated
                && Objects.equals(this.name, other.name)
                && Objects.equals(this.column, other.column)
                && Objects.equals(this.type, other.type)
                && Objects.equals(this.value, other.value);
    }
}
